# Generated by Django 4.1.4 on 2022-12-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
